name: socialsafari
description: A new Flutter project for social travel planning and booking.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.3
  fl_chart: ^0.65.0
  share_plus: ^7.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  page_transition: ^2.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_cache_manager: ^3.3.1
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/gl.png
    - lib/assets/images/fb.png
